//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ImageWindow.rc
//

// dialogs
#define			IDD_DIALOGAcquisitionSetup			100

// control ids
#define				IDOK							1
#define				IDCANCEL						2
#define				IDC_STATIC						-1
#define				IDC_EDITSTARTWAVELENGTH			1000
#define				IDC_EDITENDWAVELENGTH			1001
#define				IDC_EDITSTEPSIZE				1002
#define				IDC_NUMBEROFSTEPS				1003
#define				IDC_EDITDWELLTIME				1004
#define				IDC_EDITTIMEDELAYMULTIPLIER		1005
#define				IDC_EDITSIGNALAVERAGING			1006
#define				IDC_EDITSCANAVERAGING			1007
#define				IDC_EDITMULTIPLESCANS			1008
#define				IDC_CHKAUTOINTEGRATIONTIME		1009
#define				IDC_EDITINTTIME					1010
#define				IDC_EDITMININTTIME				1011
#define				IDC_EDITMAXINTTIME				1012
#define				IDC_EDITMINSIGNALTONOISE		1013
#define				IDC_EDITMAXSIGNALTONOISE		1014
#define				IDC_CHKPULSEDMODE				1015
#define				IDC_CHKCONTINUOUS				1016
#define				IDC_DACSETUP					1017
#define				IDC_SLITSSETUP					1018
#define				IDC_FILTERWHEELSETUP			1019
#define				IDC_CHECKINTEGRATIONTIMEON		1020
#define				IDC_SETUPAUTOINTEGRATIONTIME	1021
#define				IDC_STARTSCAN					1022
#define				IDC_CHKSAMPLE					1023
#define				IDC_CHKINTENSITYCALIBRATION		1024
#define				IDC_CHKBACKGROUND				1025
#define				IDC_DATASETUP					1026
#define				IDC_EDITWAVELENGTH				1027
#define				IDC_UPDWAVELENGTH				1028
#define				IDC_PRGSIGNALLEVEL				1029
#define				IDC_MONOCHROMATORSETUP			1030
#define				IDC_SETWAVELENGTH				1031
#define				IDC_SETUPACQMODE				1032
#define				IDC_EDITWORKINGDIRECTORY		1033
#define				IDC_BROWSEWORKINGDIRECTORY		1034
#define				IDC_EDITCOMMENT					1035

// strings
#define				IDS_EDITWORKINGDIRECTORY		1
#define				IDS_BROWSEWORKINGDIRECTORY		2
#define				IDS_EDITCOMMENT					3
#define				IDS_EDITSTARTWAVELENGTH			4
#define				IDS_EDITENDWAVELENGTH			5
#define				IDS_EDITSTEPSIZE				6
#define				IDS_NUMBEROFSTEPS				7
#define				IDS_EDITDWELLTIME				8
#define				IDS_EDITTIMEDELAYMULTIPLIER		9
#define				IDS_EDITSIGNALAVERAGING			10
#define				IDS_EDITSCANAVERAGING			11
#define				IDS_EDITMULTIPLESCANS			12
#define				IDS_CHKSAMPLE					13
#define				IDS_CHKINTENSITYCALIBRATION		14
#define				IDS_CHKBACKGROUND				15
#define				IDS_IDOK						16
#define				IDS_CHKPULSEDMODE				17
#define				IDS_CHKCONTINUOUS				18
#define				IDS_SETUPACQMODE				19
#define				IDS_DACSETUP					20
#define				IDS_SLITSSETUP					21
#define				IDS_FILTERWHEELSETUP			22
#define				IDS_DATASETUP					23
#define				IDS_EDITWAVELENGTH				24
#define				IDS_UPDWAVELENGTH				25
#define				IDS_SETWAVELENGTH				26
#define				IDS_MONOCHROMATORSETUP			27
#define				IDS_CHECKINTEGRATIONTIMEON		28
#define				IDS_SETUPAUTOINTEGRATIONTIME	29

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40005
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
